config/routes.rb
Rails.application.routes.draw do
  get 'ripples/next' => 'ripples#next_ripple'
  get 'ripples/previous' => 'ripples#previous_ripple'
  get 'ripples/' => 'ripples#newest_ripples'
  get 'ripples/oldest' => 'ripples#oldest_ripples'
  resources :ripples
  root 'ripples#index', as: 'ripples_index' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ripple.rb
class Ripple < ApplicationRecord
  validates :name, :message, presence: true
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show, :edit, :update, :destroy]
  before_action :redirect_user, only: [:edit, :update, :destroy]
  before_action :set_page, only: [:index]

  # GET /ripples
  # GET /ripples.json
  def index
      @min_id = Ripple.minimum(:id)
      @ripples = Ripple.all.order(created_at: :desc).limit(10).offset(session[:page] * 10)
  end

  # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  # GET /ripples/1/edit
  def edit
  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)
    respond_to do |format|
      if @ripple.save
        format.html { redirect_to @ripple, notice: 'Ripple was successfully created.' }
        format.json { render :show, status: :created, location: @ripple }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ripples/1
  # PATCH/PUT /ripples/1.json
  def update
    respond_to do |format|
      if @ripple.update(ripple_params)
        format.html { redirect_to @ripple, notice: 'Ripple was successfully updated.' }
        format.json { render :show, status: :ok, location: @ripple }
      else
        format.html { render :edit }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ripples/1
  # DELETE /ripples/1.json
  def destroy
    @ripple.destroy
    respond_to do |format|
      format.html { redirect_to ripples_url, notice: 'Ripple was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def next_ripple
      session[:page] += 1
      redirect_to '/'
  end

  def previous_ripple
    session[:page] -= 1
    redirect_to '/'
  end

  def newest_ripples
    session[:page] = 0
    redirect_to '/'
  end

  def oldest_ripples
    if Ripple.count % 10 != 0
      session[:page] = Ripple.count/10.to_f.ceil
    else
      session[:page] = Ripple.count/10.to_f.ceil - 1
    end
    redirect_to '/'
  end
  private
    def set_page
      if !session[:page]
        session[:page] = 0
      end
      @page = session[:page]
    end
    def redirect_user
      redirect_to @ripple
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:name, :url, :message)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
  def contains_url ripple
    if ripple.url.present?
      if /^[(http)(https)]/.match(ripple.url[0..4])
	link_to(ripple.name, ripple.url)
      else
          link_to(ripple.name, "http://#{ripple.url}")
      end
    else
      ripple.name
    end
  end

  def get_min_id ripples
    ripples.minimum(:id)  
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Consciousmess</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="main">
      <h1>CONSCIOUS/mess</h1>
      <h3>...a stream of anonymous ramblings</h3>
    </header>
    <main class="ripple">
      <%= yield %>
    </main>
  </body>
</html>

app/views/ripples/_form.html.erb
<%= form_with(model: ripple, local: true) do |form| %>
  <% if ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ripple.errors.count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name,  "Your name or alias (required)" %>
    <%= form.text_field :name, id: :name %>
  </div>

  <div class="field">
    <%= form.label :url, "A website, yours or otherwise (optional)" %>
    <%= form.text_field :url, id: :url %>
  </div>

  <div class="field">
    <%= form.label :message, "Your message/note/quote/rant (required)" %>
    <%= form.text_area :message, id: :message, rows: 20, cols: 80 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ripples/edit.html.erb
<h1>Editing Ripple</h1>

<%= render 'form', ripple: @ripple %>

<%= link_to 'Show', @ripple %> |
<%= link_to 'Back', ripples_path %>

app/views/ripples/index.html.erb
<% if notice %>
<aside id="notice"><%= notice %></aside>
<% end %>

<table class="rippletable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ripples.each do |ripple| %>
      <tr>
        <td><%= contains_url ripple %></td>
        <td><%= truncate(ripple.message, length: 80) %></td>
	<td><%= ripple.created_at %></td>
        <td><%= link_to 'Show', ripple %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ripple', new_ripple_path %>
<% if @page > 0 %> 
  <%= link_to 'Previous 10 Ripples', ripples_previous_path %>
<% else %>
  <i id="last">Previous 10 Ripples </i>
<% end %>
<% if @ripples.count < 10 || @ripples[9].id == @min_id %>
  <i id="next">  Next 10 Ripples</i>
<% else %> 
  <%= link_to 'Next 10 Ripples', ripples_next_path %>
<% end %>
<%= link_to 'Oldest', ripples_oldest_path %>
<%= link_to 'Newest', ripples_path %>

app/views/ripples/new.html.erb
<h1>Say What's on Your Mind</h1>

<%= render 'form', ripple: @ripple %>

<%= link_to 'Back', ripples_path %>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong><%= contains_url @ripple %> said:</strong>
</p>

<p class="message">
  <%= @ripple.message %>
</p>

<%= link_to 'Back', ripples_path %>